### ISSUE TITLE
Printing Problem

### ISSUE THREAD

**Issue by Firewehr** [Firewehr/FeuerwehrBestellsystem#6]
The printer doesn't print when there is only one waiting position and "direct printing" is clicked

**Comment by Skopy77** [comment]
Fixed!
Colume 126:
if (mysqli_num_rows($result2)==1 && $row2['anzahl'] == 1) {
							echo '" onclick="kuecheGesamtFertig(' . $arrayListe . ');"/>';
							}
							else {
                            echo '" onclick="kuecheFertig(' . $row2['rowid'] . ');"/>';
							}
