### ISSUE TITLE
Zusatzinfo

### ISSUE THREAD

**Issue by Firewehr** [Firewehr/FeuerwehrBestellsystem#9]
Wenn bei einer Bestellung eine Zusatzinfo vorhanden ist, lässt sich diese nicht einzeln in Schank oder Küche abschließen.

**Comment by Skopy77** [comment]
Es ist aufgrund des <br>, was nicht erlaubt ist bei <input>. Dafür gibt es 3 Lösungen, die letzen 2 können aber dazu führen, dass sie nicht mehr unter Chrome oder Safari funktionieren.
https://css-tricks.com/snippets/html/button-with-line-breaks/

**Comment by Skopy77** [comment]
Fix Issue#9 (doppelzeilige Zusatzinfo)
Anstelle von <input> wurde <button> verwenden, denn dort geht ein Zeilenumbruch <br>
